function [e,errmsg] = MSXgeterror(errcode,len)    
% Declaration:
%  [e,errmsg] = MSXgeterror(errcode,len);
% 
% Description:
%  Returns the text for an error message given its error code.
% 
% Arguments:
%  errcode: is the code number of an error condition generated by EPANET-MSX;
% 
%  msg: is a C-style character string that is returned containing the text of
%       the error message corresponding to the error code;
% 
%  len: is the maximum number of characters that msg can contain.
% 
% Returns:
%  Returns an error code or 0 for no error.
% 
% Notes:
%  msg should be sized to accept a minimum of 80 characters.
% 
%  This function only applies to error codes generated by the MSX toolkit.
%  There is a comparable EPANET toolkit function, ENgeterror, that applies
%  to EPANET errors.

global MSXDLLNAME;

errcode=int32(errcode);
len=int32(len);
errmsg=char(32*ones(1,len+1));
[e,errmsg] = calllib(MSXDLLNAME,'MSXgeterror',errcode,errmsg,len);
if e MSXerror(e); end
